# Generated by Django 4.2 on 2023-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='phone',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
